# Generated by Django 4.2.23 on 2025-06-17 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thriftapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thriftitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thrift_items/'),
        ),
        migrations.AddField(
            model_name='thriftitem',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thrift_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
